openapi: 3.0.3
info: { title: Sample Petstore, version: 1.0.0 }
paths:
  /pets:
    get: { responses: {'200': { description: ok }} }
    post:
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Pet' }
      responses: {'201': { description: created }}
components:
  schemas:
    Pet:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        owner_email: { type: string }
